services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'      
      - '443:443'    
      - '81:81'     
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

  # --- ADGUARD HOME ---
  adguardhome:
    image: 'adguard/adguardhome:latest'
    container_name: adguard-home
    restart: unless-stopped
    ports:
      - '53:53/tcp'      
      - '53:53/udp'     
      - '3000:3000/tcp'  
      - '8080:80/tcp'    
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf